version: "3.7"

services:
  game-chess:
    container_name: game-chess
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "$API_PORT:$API_PORT"
    env_file: .env
    restart: always
volumes:
  requestLog: